[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.2.101
lib_deps =
    majicdesigns/MD_Parola@^3.7.3
    majicdesigns/MD_MAX72XX@^3.5.1
    bblanchon/ArduinoJson@^7.0.0
    beegee-tokyo/DHT sensor library for ESPx@^1.19.0
